name: oneiro
description: "Rüya analiz ve takip uygulaması"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '3.8.1'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase Paketleri
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  
  
  # UI & Animasyon
  lottie: ^3.1.0
  flutter_svg: ^2.0.10
  google_fonts: ^6.0.0
  shimmer: ^3.0.0
  
  # Auth
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.0
  firebase_messaging: ^16.0.0
  # State Management
  provider: ^6.1.2
  flutter_riverpod: ^2.4.9
  
  # HTTP & API
  http: ^1.2.1
  dio: ^5.4.0
  
  # Diğer
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.3.0
  font_awesome_flutter: ^10.9.0
  permission_handler: ^12.0.1 #bildirim
  connectivity_plus: ^5.0.2 #internet baglanti kontrolü
  
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/svg/
    
    
  # fonts:
  #   - family: SpaceGrotesk
  #     fonts:
  #       - asset: assets/fonts/SpaceGrotesk-Regular.ttf
  #       - asset: assets/fonts/SpaceGrotesk-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/SpaceGrotesk-Bold.ttf
  #         weight: 700
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

